import 'package:bevy/src/models/contact_model.dart';

List<ContactModel> contacts = [
  ContactModel(
    avatar: 'https://picsum.photos/200',
    name: 'Diego',
    message: 'hola',
    status: true,
    delete: false,
    idChat: '0',
    id: '0',
    idCanvas: '0',
  ),
  ContactModel(
    avatar: 'https://picsum.photos/200',
    name: 'Pepe',
    message: 'donde estas?',
    status: true,
    delete: false,
    idChat: '1',
    id: 'Fk8zzie69FQsrwTpO0rB',
    idCanvas: '1',
  ),
  ContactModel(
    avatar: 'https://picsum.photos/200',
    name: 'Jose',
    status: false,
    delete: false,
    idChat: '2',
    id: 'E4dUso2X3gPqvlJBQ8jY',
    idCanvas: '2',
  ),
  ContactModel(
    avatar: 'https://picsum.photos/200',
    name: 'Carlos',
    message: 'como te encuentras?',
    status: true,
    delete: false,
    idChat: '3',
    id: 'adwvOhfNIZGIptpfUgUV',
    idCanvas: '3',
  ),
  ContactModel(
    avatar: 'https://picsum.photos/200',
    name: 'Juan',
    status: false,
    delete: false,
    idChat: '4',
    id: '4',
    idCanvas: '4',
  ),
  ContactModel(
    avatar: 'https://picsum.photos/200',
    message: 'todo correcto',
    name: 'Matias',
    status: true,
    delete: false,
    idChat: '5',
    id: '5',
    idCanvas: '5',
  ),
];
