import 'package:bevy/src/models/user_model.dart';

List<UserModel> users = <UserModel>[
  UserModel(
    id: 'VgSARMN0q8pLTdKV0Z5N',
    name: 'Diego',
    email: 'diego@gmail.com',
    password: '0',
    idcontacts: ['3', '1', '2'],
    idcanvas: ['0', '1', '2'],
    idSettings: '0',
    avatar: 'https://picsum.photos/200',
    idContact: '0',
  ),
  UserModel(
    id: '1',
    name: 'Pepe',
    email: 'pepe@gmail.com',
    password: '1',
    idcontacts: ['3', '4', '5'],
    idcanvas: ['0', '1', '2'],
    idSettings: '1',
    avatar: 'https://picsum.photos/200',
    idContact: '1',
  ),
  UserModel(
    id: '2',
    name: 'Jose',
    email: 'jose@gmail.com',
    password: '2',
    idcontacts: ['6', '0', '1'],
    idcanvas: ['0', '1', '2'],
    idSettings: '2',
    avatar: 'https://picsum.photos/200',
    idContact: '2',
  ),
  UserModel(
    id: '3',
    name: 'Carlos',
    email: 'carlos@gmail.com',
    password: '3',
    idcontacts: ['5', '4', '3'],
    idcanvas: ['0', '1', '2'],
    idSettings: '3',
    avatar: 'https://picsum.photos/200',
    idContact: '3',
  ),
  UserModel(
    id: '4',
    name: 'Juan',
    email: 'juan@gmail.com',
    password: '4',
    idcontacts: ['2', '1', '0'],
    idcanvas: ['0', '1', '2'],
    idSettings: '4',
    avatar: 'https://picsum.photos/200',
    idContact: '4',
  ),
  UserModel(
    id: '5',
    name: 'Matias',
    email: 'matias@gmail.com',
    password: '5',
    idcontacts: ['5', '2', '1'],
    idcanvas: ['0', '1', '2'],
    idSettings: '5',
    avatar: 'https://picsum.photos/200',
    idContact: '5',
  ),
];
